Update JamfClassicAPIObjectUploaderBase.py
Fixes the following error if you use more than one instance of this processor in a recipe and create different object types:

```
The following objects were updated in Jamf Pro:
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2786, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2782, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 2385, in run_recipes
    this_row.append(row[field])
KeyError: 'mobile_device_extension_attribute'
```